server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  zipkin:
    base-url: http://localhost:8081/
  datasource:
    url: jdbc:h2:file:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
  cloud:
    stream:
      default:
        contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181
      bindings:
        smsOutput:
          destination: sms
  jackson:
    serialization:
      write-dates-as-timestamps: false

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 360000
        loggerLevel: basic

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 180000

interceptors:
  base-package: au.co.nab.poc.order.config.interceptor
  name: AclInterceptor

voucherThirdParty:
  url: http://localhost:7000
  waitTimeout: 30 #seconds